"""add create_date to episode table

Revision ID: 53dfc6100e78
Revises: afa7b6c5cc9d
Create Date: 2025-06-29 23:28:03.758463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dfc6100e78'
down_revision: Union[str, Sequence[str], None] = 'afa7b6c5cc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'create_date')
    # ### end Alembic commands ###
