"""add audio file size and type

Revision ID: a44826fec1f7
Revises: 93ea1ec1415a
Create Date: 2025-06-28 20:06:23.727157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a44826fec1f7'
down_revision: Union[str, Sequence[str], None] = '93ea1ec1415a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('audio_file_size', sa.Integer(), nullable=True))
    op.add_column('episode', sa.Column('audio_file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'audio_file_type')
    op.drop_column('episode', 'audio_file_size')
    op.create_table('episodes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('webpage_url', sa.VARCHAR(), nullable=False),
    sa.Column('upload_date', sa.VARCHAR(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), nullable=True),
    sa.Column('audio_file', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webpage_url')
    )
    # ### end Alembic commands ###
