"""init episode table

Revision ID: afa7b6c5cc9d
Revises:
Create Date: 2025-06-29 23:14:24.454564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "afa7b6c5cc9d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episode",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("webpage_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("upload_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("thumbnail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_file", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_file_size", sa.Integer(), nullable=True),
        sa.Column("audio_file_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("webpage_url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("episode")
    # ### end Alembic commands ###
