services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.13
    container_name: vpodcasts-dev
    volumes:
      - ..:/workspaces/vpodcasts:cached
    command: sleep infinity

    ports:
      - "5180:5180"
      - "5080:5080"

    user: vscode
    networks:
      - vpodcasts-dev

  nats:
    image: nats:alpine
    container_name: vpodcasts-dev-nats
    networks:
      - vpodcasts-dev

networks:
  vpodcasts-dev:
    driver: bridge

