name: vpodcasts_devcontainer
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.13
    container_name: vpodcasts-dev
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ..:/workspaces/vpodcasts:cached
    command: sleep infinity

    ports:
      - "5180:5180"
      - "5080:5080"

    user: vscode
    networks:
      - vpodcasts-dev

  nats:
    image: nats:alpine
    container_name: vpodcasts-dev-nats
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["-js"]
    networks:
      - vpodcasts-dev

networks:
  vpodcasts-dev:
    driver: bridge

